#!/usr/bin/env bash
# displays the time for 12 hours 59 minutes

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [$minutev-le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
